services:
  app:
    image: node:22-alpine
    command: sh -c "yarn install && yarn run dev"
    mem_limit: 512m
    cpus: 0.5
    ports:
      - 127.0.0.1:3000:3000
    networks:
      - mynetwork
    working_dir: /app
    volumes:
      - ./:/app
    environment:
      MYSQL_HOST: mysql
      MYSQL_USER: root
      MYSQL_PASSWORD: secret
      MYSQL_DB: todos

  mysql:
    image: mysql:8.0
    ports:
        - "127.0.0.1:3306:3306"  # localhost:3306
    volumes:
      - todo-mysql-data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: todos
    networks:
      - mynetwork

networks:
  mynetwork:
    external: true

volumes:
  todo-mysql-data:
